### ISSUE TITLE
[Feature Request] Event preview & editing in Timeline view

### ISSUE THREAD

**Issue by 1xWill** [mark-when/obsidian-plugin#4]
Appreciate your work for bringing this great tool in Obsidian.

It would be nice for these features to be added in timeline view in obsidian:
- preview event details
- add/edit/delete an event directly

The latest version(0.0.2) only allows editing in note view.
While the timeline view seems to be read-only, actions such as dragging, clicking "+", or clicking on events do not have any effect. Or is this a bug that I was encountering?

**Comment by TomSz84** [comment]
I would like to know if this is a new feature, or simply this is a bug and those features do not work properly?

Anyway, this is supercool plugin!

**Comment by kochrt** [comment]
Editing from the timeline is supported in [0.0.3](https://github.com/mark-when/obsidian-plugin/releases/tag/0.0.3)

**Comment by RashoAli** [comment]
Thanks for the very useful plugin. 
Maybe I have installed the wrong version, but currently, I have version 0.0.3 and I am still facing the same problem as @1xWill. Did I miss something during the installation?
