### ISSUE TITLE
Can not scroll up/down long images with plugin enabled

### ISSUE THREAD

**Issue by lutherstrike** [mark-when/obsidian-plugin#9]
### What happened?

Thanks for making this fantastic plugin, I really enjoy using it. 

Here are some problems I encountered while using this. 
Without this plugin, when I open large image files within Obsidian, like JPEG or PNG, I can scroll up & down to view the images.

After I enabled this plugin, the scroll bar just disappeared. 

### What did you expect to happen?

I am wondering if some configurations are created globally, maybe some exceptions for certain file types can solve this?

### How can we reproduce it (as minimally and precisely as possible)?

1. Put some large or long image files (jpeg, png, etc.) in your Obsidian vault.
2. Open it within the Obsidian.
3. Can not scroll up or down to browse the images.

### Plugin version

0.0.1

### Obsidian version

1.5.12

**Comment by Acylation** [comment]
Confirmed and this is probably a css issue. Will draft a fix in day. Thanks for your report!

**Comment by Acylation** [comment]
I've bumped to the 0.0.2 version and updated the release files. Now the problem should be fixed if you reinstall/update Markwhen.

**Comment by lutherstrike** [comment]
Thanks for the swift fix!
